spring:
  main:
    banner-mode: off
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hello_world
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

server:
  http2:
    enabled: true
